# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
#         cache: 'npm'
    - run: npm i
    - run: npm install -g @c8y/cli
    - run: npm run build --if-present
    - run: copy cumulocity.json dist
    - name: Copy build folder contents to the dist folder
      run: |
        mv dist/login-app/* dist/
        rm -r dist/login-app
    - run: npm test
    - run: |
       if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "Branch Name ******* ${{ github.ref }}"
          echo "Deploy to Main"
          c8ycli deploy -u https://env555200.eu-latest.cumulocity.com -U post2mohankiran@gmail.com -P Mohan@kiran12 dist
       else
          echo "Deploy to Master"
          c8ycli deploy -u https://env320490.eu-latest.cumulocity.com -U NewUser -P abcdABCD@1234 dist
