# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
#         cache: 'npm'
    - run: npm i
    - run: npm install -g @c8y/cli
    - run: npm run build --if-present
    - run: ls
    - run: copy cumulocity.json dist
    - run: ls
    - name: Copy build folder contents to the dist folder
      run: |
        mv dist/login-app/* dist/
        rm -r login-app
    - run: ls
    # - name: Copy build folder contents to the dist folder
    #   run: |
    #     cp -R dist/login-app/. dist/
    # - run: ls
    - run: npm test
    - run: npm run deploy
